# the method for using conda within travis has been
# adapted from: https://conda.io/docs/travis.html

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
#  - pip install numpy
#  - pip install scipy
#  - git clone https://multiply-ci:multiplyci1@github.com/CCI-Tools/cate.git
#  - cd cate
#  - python setup.py install
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda list

  # nose must be installed explicitly to ensure that the virtual conda-environment is used within the tests
  # (otherwise import-errors will occur for non-standard packages like scipy sympy and symengine)
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest numpy
  - source activate test-environment
  - conda list

  # before the actual installation we test first if existing
  # installation mechanism using PIP and CONDA work
  # with the versioned package on PyPi. Please note
  # that this is not necessarily the same code as in the current development
  # or master branches
  - conda install pip

  # test installation from pip
  #- pip install rt1
  #- yes | pip uninstall rt1

  # test conda based installation (currently not activated as package still missing)
  # - conda install -c conda-forge rt1
  # - conda uninstall -c conda-forge rt1
  #
  # now install the MULTIPLY components (could be replaced at a later stage with alternative installation methods)
  #
  - pip install cython
  - pip install proj4
  - pip install cartopy
  - pip install dask
  - pip install geopandas
  - pip install fiona
  - pip install jdcal
  - pip install matplotlib
  - pip install netcdf4
  - pip install numba
  - pip install numpy
  - pip install owslib
  - pip install pandas
  - pip install pillow
  - pip install psutil
  - pip install pyproj
  - pip install scipy
  - pip install shapely
  - pip install tornado
  - pip install xarray
  - pip install https://github.com/CCI-Tools/cate/zipball/master
  - pip install https://github.com/multiply-org/prior-engine/zipball/master
  - pip install https://github.com/multiply-org/data-access/zipball/master
  - pip install https://github.com/multiply-org/emulation-framework/zipball/master
  - pip install https://github.com/multiply-org/forward-operators/zipball/master
  - pip install https://github.com/multiply-org/post-processing/zipball/master
  - pip install https://github.com/multiply-org/coarse-res-pre-processing/zipball/master
  - pip install https://github.com/multiply-org/high-res-pre-processing/zipball/master
  - pip install https://github.com/multiply-org/sar-pre-processing/zipball/master
  - pip install https://github.com/multiply-org/inference-engine/zipball/master
  - pip install https://github.com/multiply-org/visualization/zipball/master
  - pip install https://github.com/multiply-org/multiply-core/zipball/master

script:
  - pytest
