channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6*
  - gdal>2.1
  - poppler<0.66
  - cftime
  - mock = 2.0.0
  - pip
  - pip:
    - sentinelhub
    - netCDF4
    - pyyaml
    - matplotlib
    - xarray
    - sphinxcontrib-bibtex
    - very-good-setuptools-git-version



